version: "3.8"

networks:
    atpay-network:

services:
    postgres:
        image: postgres:latest
        container_name: wallet-ledger-database
        restart: always
        environment:
            POSTGRES_DB: wallet_ledger
            POSTGRES_USER: root
            POSTGRES_PASSWORD: "P@sSwOrD"
            TZ: "Asia/Ho_Chi_Minh"
        ports:
            - "5432:5432"
        networks:
            - atpay-network
        volumes:
            - wallet-ledger-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root -d wallet_ledger"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    wallet-ledger-data:
