# ========== DATASOURCE (overridden by docker-compose env vars) ==========
spring.datasource.url=jdbc:postgresql://at-pay-db:5432/wallet_ledger
spring.datasource.username=root
spring.datasource.password=P@sSwOrD

# ========== LOGGING: ship to Logstash ==========
at-logger.logstash.host=logstash
at-logger.logstash.port=5000
